spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: update # JPA ?? DDL ??
    show-sql: true # SQL ?? ?? ??
    properties:
      hibernate:
        connection:
          characterEncoding: UTF-8
          useUniCode: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
      encoding: UTF-8


jwt:
  key: ${JWT_SECRET_KEY} # JWT ??? ?
  access-token-expiration-minutes: 100
  refresh-token-expiration-minutes: 200

