spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: update # JPA ?? DDL ??
    show-sql: true # SQL ?? ?? ??
    properties:
      hibernate:
        connection:
          characterEncoding: UTF-8
          useUniCode: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  security:
    oauth2:
      client:
        registration:
          google:
            # ??? ???
            redirect-uri: http://ec2-52-78-205-102.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/google
            client-id: ${G_CLIENT_ID}
            client-secret: ${G_CLIENT_SECRET}
            scope:
              - email
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
      encoding: UTF-8


jwt:
  key: ${JWT_SECRET_KEY} # JWT ??? ?
  access-token-expiration-minutes: 100
  refresh-token-expiration-minutes: 200

